language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - sudo apt-get update --yes && sudo apt-get install graphviz
  - pip install .[plot]
  - pip install pytest flake8
script:
  - cd tests && MATPLOTLIBRC="../ci" pytest ./ && cd ../
  - flake8 src
cache: pip
